#!/usr/bin/env bash
# Configures a new Ubuntu machine to install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debain.html
sudo service nginx start
