#!/usr/bin/env bash
# Install and configure HAproxy for load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "9i ENABLED=1\n" /etc/default/haproxy
sudo sed -i "$ a\ \nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 819-web-01 34.74.48.25:80 check\n\tserver 819-web-02 52.207.228.69:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
