#!/usr/bin/env bash
# Script that creates file containing pid, displays indefinitly
# Displays on sigterm and sigint, deletes pid file on sigquit and sigterm

echo "$$" > /var/run/holbertonscript.pid
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"
rm /var/run/holbertonscript.pid
exit' SIGTERM
trap 'rm /var/run/holbertonscript.pid
exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
